CREATE TABLE `tsupplier` (
	`kodesup` VARCHAR(15) NULL DEFAULT NULL,
	`nama` VARCHAR(30) NULL DEFAULT NULL,
	`alamat` VARCHAR(35) NULL DEFAULT NULL,
	`telepon` VARCHAR(14) NULL DEFAULT NULL,
	`perusahaan` VARCHAR(40) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=MyISAM
;
